# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TithJbCtmUbJsfIiKPHIRcWyYC/ZskXz1y7Pg3w7Dvx0YRnU+t71T4ovzrkBL6Juy1DCLkBzTkUiycHX3cylIEZrAdV7T69bSx7Cl2EeFp5hpLZPmeaDoxXs2yGINrTp+krI6YZyVAFNGV+vJlp67hGzNqYEfJHBVoU+YqeKmhJskVUZVYreFU4Mnkc1LdD1WF0vyIWvoFEBPmRIcR3NVf0NBPJWkw05sD6/6m6ZJVfoJBWjRnCBiNR0WqI2WI5rVBiazKVFQqNc3D5VKS5VSZENV6k+SmuFIjeM7b5nBIrCtuQtqx9krui7Rbm7gUnbEGUsazdkMa+YWSzkxwmrrxTMY9rXesgQP5Itz3vT7ngkmCkL1ddPIlGS80gv1Qa2GCiU1HzVlMid/W5v/c7ZTjTg44b89UvIvgraYtIMHSFHex6NI6aoS8g8MsQmkFwfyHgG7/9oPkCjNq8LrYVReUeWYlJGtF+YNAljjDt0Hk6HLfNfWBznZlEqg+HtpmWTTX9ZudqSqSmkDR6M8S3Tv8RnBvQ6RwYk4iohd+s0R/SvBBZu9nuRkoFFAnqTB3uWoM6uc1rUUyEStBVcqKljPCbUwEvx9zXBQyejEUcit8iCjY7H5Ao33P0ScUm+l6fN7o5TQA8BsKLhscPQ0sRnqCRdx85bDDvTt46DAETlz7w="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
