travis:
  secure:
    BINSTAR_TOKEN: HdEQ+Isb6Sn2RQ9lJ3kG2nv9UMLMgcgftzGCegccaw+GfxG5RHNzTRHU0i3eY8TFTtGPHQ1qacHjmgeXqbzojf6OZKno1NYvwltbA1PjyyMF7+lAf+n2QT67rDUaU2XPbjW8hDLP0hgsNFhEeoiC+FEAQmjBr/aOiog+5QtDXBwjaU5ml/IeM9lny5QPiuOeIwebu04CZQ44j1DGELom00JoT6FeG7bvVKYFckoaRAMsOFwDv+iXKrAf5b5oYStgC3mU0uRMrFeTrESGHydHGozPOJbtYYsplbRqIisg/IOZVMVyuCXxfXwcCHXpNCQF4R2crpoYWQQNJJPudKYMBdkRT10Wr4cMuxU609/52/OzvgW55UhKJWHcv/dh1DMm7wHl0T0mANb7Mi3cE+3O5adzDbIo/k/VE2a30CFFUKbgHwFRyNOMLPygwG/wlZVBG7wx4hDtXgFb2zqVUVl3e6sYaB63uzmAt6RdoBI9pWUmG9kKDPigHS/dhXpksqYMWCZKlIpztA729q4LW+RNifueUB35WXirO4lgSITDVnpwm4Qj1qn9cBYmJTtV5DJ+nnsZXqr8T22R/+CmG8QrhD+yAnuH5B8pJZpFBCUcOmAB6RTo9yJ2gjUW6/1Tm8B3i8ZUp11pc6r0V6+3d+/Yd/tw0GlrlyPCtPbhwlRrcZI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
