travis:
  secure:
    BINSTAR_TOKEN: TithJbCtmUbJsfIiKPHIRcWyYC/ZskXz1y7Pg3w7Dvx0YRnU+t71T4ovzrkBL6Juy1DCLkBzTkUiycHX3cylIEZrAdV7T69bSx7Cl2EeFp5hpLZPmeaDoxXs2yGINrTp+krI6YZyVAFNGV+vJlp67hGzNqYEfJHBVoU+YqeKmhJskVUZVYreFU4Mnkc1LdD1WF0vyIWvoFEBPmRIcR3NVf0NBPJWkw05sD6/6m6ZJVfoJBWjRnCBiNR0WqI2WI5rVBiazKVFQqNc3D5VKS5VSZENV6k+SmuFIjeM7b5nBIrCtuQtqx9krui7Rbm7gUnbEGUsazdkMa+YWSzkxwmrrxTMY9rXesgQP5Itz3vT7ngkmCkL1ddPIlGS80gv1Qa2GCiU1HzVlMid/W5v/c7ZTjTg44b89UvIvgraYtIMHSFHex6NI6aoS8g8MsQmkFwfyHgG7/9oPkCjNq8LrYVReUeWYlJGtF+YNAljjDt0Hk6HLfNfWBznZlEqg+HtpmWTTX9ZudqSqSmkDR6M8S3Tv8RnBvQ6RwYk4iohd+s0R/SvBBZu9nuRkoFFAnqTB3uWoM6uc1rUUyEStBVcqKljPCbUwEvx9zXBQyejEUcit8iCjY7H5Ao33P0ScUm+l6fN7o5TQA8BsKLhscPQ0sRnqCRdx85bDDvTt46DAETlz7w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
